/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   nuxeo-routing-behavior.html
 */

// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/**
 * `Nuxeo.RoutingBehavior` provides a `urlFor` helper function for reverse routing.
 */
declare module "@nuxeo/nuxeo-ui-elements/nuxeo-routing-behavior.js" {
  interface RoutingBehavior {
    __router: object | null | undefined;
    router: object | null | undefined;
    readonly urlFor: Function | null | undefined;
    readonly navigateTo: Function | null | undefined;
    attached(): void;
    detached(): void;
    _updateRouter(): void;

    /**
     * Caches the router
     */
    _routerChanged(router: any): void;

    /**
     * Returns a computed `urlFor` method, based on the current `router`.
     */
    _computeUrlFor(): any;

    /**
     * Returns a computed `navigateTo` method, based on the current `router`.
     * Invokes `router.navigate` to trigger the actual navigation.
     */
    _computeNavigateTo(): any;
  }

  const RoutingBehavior: RoutingBehavior;
}
