/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   nuxeo-elements.html
 */

// tslint:disable:variable-name Describing an API that's defined elsewhere.

/// <reference path="nuxeo-connection.d.ts" />
/// <reference path="nuxeo-resource.d.ts" />
/// <reference path="nuxeo-document.d.ts" />
/// <reference path="nuxeo-operation.d.ts" />
/// <reference path="nuxeo-page-provider.d.ts" />
/// <reference path="nuxeo-audit-page-provider.d.ts" />
/// <reference path="nuxeo-search.d.ts" />
