/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   nuxeo-search.html
 */

// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="nuxeo-element.d.ts" />
/// <reference path="nuxeo-resource.d.ts" />

declare namespace Nuxeo {
  /**
   * `nuxeo-search` allows managing saved searches on a Nuxeo server.
   *
   *     <nuxeo-search></nuxeo-search>
   *
   * Example - Get all saved searches accessible by the current user:
   *
   *     <nuxeo-search auto searches="{{searches}}"></nuxeo-nuxeo-search>
   *
   * Example - Get a saved search by id:
   *
   *     <nuxeo-search auto search-id="[[id]]" search="{{search}}"></nuxeo-search>
   *
   * Example - Execute a saved search:
   *
   *     <nuxeo-search auto search-id="[[id]]" results="{{results}}"></nuxeo-search>
   *
   * You can trigger a method explicitly by calling `get`, `post`, `put`, `remove` or `execute` on the
   * element.
   */
  class Search extends Nuxeo.Element {
    /**
     * Id of a saved search to be used on requests.
     */
    searchId: string | null | undefined;

    /**
     * Body to be used on POST/PUT requests.
     */
    data: object | null | undefined;

    /**
     * A single saved search as a result of a GET request with a given id.
     */
    search: object | null | undefined;

    /**
     * Saved searches accessible by the current user.
     * Result of a GET request when an id is not specified.
     */
    searches: any[] | null | undefined;

    /**
     * Results when executing a given saved search.
     */
    results: any[] | null | undefined;

    /**
     * Computed path of the search endpoint to use.
     */
    readonly path: string | null | undefined;

    /**
     * Search parameters.
     */
    params: object | null | undefined;

    /**
     * The id of a nuxeo-connection to use.
     */
    connectionId: string | null | undefined;

    /**
     * If true, automatically execute the search request.
     */
    auto: boolean | null | undefined;

    /**
     * The HTTP method to use ('GET', 'POST', 'PUT', or 'DELETE'). Default is 'GET'
     */
    method: string | null | undefined;

    /**
     * The headers of the request.
     */
    headers: object | null | undefined;

    /**
     * The delay in milliseconds to debounce the auto fetch call.
     */
    autoDelay: number | null | undefined;

    /**
     * True while requests are in flight.
     */
    readonly loading: boolean | null | undefined;
    ready(): void;

    /**
     * Gets the list of saved searches or the current search search if `search-id` is set.
     */
    get(): any;

    /**
     * Saves the search.
     */
    post(): any;

    /**
     * Updates the saved search.
     */
    put(): any;

    /**
     * Deletes the saved search.
     */
    remove(): any;

    /**
     * Executes the saved search.
     */
    execute(): void;
    _computePath(): any;
    _autoChanged(): void;
  }
}

interface HTMLElementTagNameMap {
  'nuxeo-search': Nuxeo.Search;
}
