/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   nuxeo-document.html
 */

// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="nuxeo-element.d.ts" />
/// <reference path="nuxeo-resource.d.ts" />

declare namespace Nuxeo {
  /**
   * `nuxeo-document` allows managing Documents on a Nuxeo server.
   *
   *     <nuxeo-document auto doc-path="/default-domain"></nuxeo-document>
   *
   * With `auto` set to `true`, the GET method is executed whenever
   * its `docPath` or `docId` properties are changed.
   *
   * You can trigger a method explicitly by calling `get`, `post`, `put` or `delete` on the
   * element.
   */
  class DocumentElement extends Nuxeo.Element {
    /**
     * The id of a nuxeo-connection to use.
     */
    connectionId: string | null | undefined;

    /**
     * If true, automatically execute the operation when either `path` or `params` changes.
     */
    auto: boolean | null | undefined;

    /**
     * The HTTP method to use ('GET', 'POST', 'PUT', or 'DELETE'). Default is 'GET'
     */
    method: string | null | undefined;

    /**
     * The document id. Either 'docId' or 'docPath' must be defined.
     */
    docId: string | null | undefined;

    /**
     * The document path. Either 'docId' or 'docPath' must be defined.
     */
    docPath: string | null | undefined;

    /**
     * The path of the resource.
     */
    readonly path: string | null | undefined;

    /**
     * The parameters to send.
     */
    params: object | null | undefined;

    /**
     * The data to pass to the server.
     */
    data: object | null | undefined;

    /**
     * The response from the server.
     */
    response: object | null | undefined;

    /**
     * The `entity-type` of the resource.
     */
    type: string | null | undefined;

    /**
     * The headers of the request.
     * 'Accept': 'text/plain,application/json' is already set by default.
     */
    headers: object | null | undefined;

    /**
     * The `content enricher` of the resource.
     * Can be an object with entity type as keys or list or string (which defaults to `document` entity type).
     */
    enrichers: object | null | undefined;

    /**
     * List of comma separated values of the document schemas to be returned.
     * All document schemas are returned by default.
     */
    schemas: string | null | undefined;

    /**
     * If true, documents changed by the call will be reindexed synchronously server side.
     */
    syncIndexing: boolean | null | undefined;

    /**
     * True while requests are in flight.
     */
    readonly loading: boolean | null | undefined;
    ready(): void;

    /**
     * Fetch the document.
     */
    get(): any;

    /**
     * Create the document.
     */
    post(): any;

    /**
     * 'Update the document.
     */
    put(): any;

    /**
     * Delete the document.
     */
    remove(): any;

    /**
     * Execute the request.
     */
    execute(): any;
    _computePath(docId: any, docPath: any): any;
  }
}

interface HTMLElementTagNameMap {
  'nuxeo-document': Nuxeo.DocumentElement;
}
